### ISSUE TITLE
Cryptic error in config parser when the pipeline key is wrong

### ISSUE THREAD

**Issue by matbun** [interTwin-eu/itwinai#352]
**Describe the bug**
Running the pipeline with the wrong `pipe_key` causes cryptic error message.

**To Reproduce**

Assuming pipeline 

```yaml
# Pipeline of pipelines 
pop:
  _target_: itwinai.pipeline.Pipeline
  name: parent pipeline
  steps:
    pipeline1:
      _target_: itwinai.pipeline.Pipeline
      name: first pipeline
      steps:
        datagetter:
          _target_: itwinai.tests.dummy_components.FakeGetter
          data_uri: path/to/data
    pipeline2:
      _target_: itwinai.pipeline.Pipeline
      name: second pipeline
      steps:
        datagetter:
          _target_: itwinai.tests.dummy_components.FakeGetter
          data_uri: path/to/data
```

```bash
itwinai exec-pipeline +pipe_key pippo
```

Moreover, it is a common mistake to confuse `+pipe-key` with `+pipe_key`, which at the moment fails silently, resulting in the option to be silently ignored.

```bash
itwinai exec-pipeline +pipe-key pippo
```

**Expected behavior**

Should raise more explicit errors to explain to the user what's wrong.
